language: node_js
node_js:
- '0.11'
before_install:
- cp ci/travis-ci.sh $HOME/
- chmod +x $HOME/travis-ci.sh
- $HOME/travis-ci.sh before-install
before_script:
- $HOME/travis-ci.sh before-script
script:
- $HOME/travis-ci.sh script
after_script:
- $HOME/travis-ci.sh after-script
after_success:
- $HOME/travis-ci.sh after-success
before_deploy:
- $HOME/travis-ci.sh before-deploy
- cd built
after_deploy:
- $HOME/travis-ci.sh after-deploy
cache:
  directories:
  - node_modules
notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalamuna.com
    - ben@kalamuna.com
    - coder1@gmail.com
    on_success: always
deploy:
  provider: npm
  email:
    secure: Y9wveqCc7ZbJcGGCKS+mhZ/rJZvkpfguvcaskTgjpCil4+FNmY04uJphTHripRok9jT/GTsreLNk4pPbilNCzj746wHZeMET0AcnBNAhvNn+8MKzJk9RSVstsmlAMB1dQaBwjK1KBIB97G3M94mOzU1YPh7kxvFP1SRuKumllys=
  api_key:
    secure: hvTYEvSXO6/C6MSwOGJYWGVIAWKYXY41qHqbOg7H2O/+VqkefqrjNMbA4XyEdIvZ2EVSrlAHCxe9tUJj9kF4WDVHT4O1gbPLCcuDSYW68B2Xb+hQ4IUxJ8C3FmV/+hFmg6+InBtCK+wHuGOeRqCSxjwZk55frX0m5SZcLbHmXqI=
  on:
    repo: kalabox/kalabox
    branch: master
