language: node_js
sudo: required
matrix:
  include:
  - os: linux
    env: KBOX_PKG_TYPE=rpm
    node_js: '4.2'
  - os: linux
    env: KBOX_PKG_TYPE=deb KBOX_SUDO_PASSWORD= DOCKER_HOST=tcp://10.13.37.100:2375
    node_js: '4.2'
  - os: osx
    env: KBOX_PKG_TYPE=dmg
    node_js: '4.2'
services:
  - docker

before_install:

  # Nice dev helpers
  - ./scripts/travis-env.sh

  # Install some node deps
  - npm install -g grunt-cli

before_script:

  # Sanity checks
  - node --version
  - npm --version
  - grunt --version
  - node_modules/jxcore/bin/jx --version
  - node_modules/jxcore/bin/jx --jxversion
  - ruby --version
  - gem --version

script:

  # Run code and styling
  - grunt test:code
  - grunt test:unit

  # Run the build
  - ./scripts/build-travis.sh
  - ls -lsa dist/

before_deploy:

  # Do some basic tests of our build
  - echo "test"

notifications:
  irc:
  - chat.freenode.net#kalabox
  email:
    recipients:
    - mike@kalabox.io
    - alec@kalabox.io
    on_success: always
deploy:
  - provider: releases
    api_key:
      secure: MDL8ub5md5MQFhcZrsX15qEJ9pJPrQ2jIzFQNergsXh3D0bEO3mNbeCcN9kI2S6chUIxpxwvoJnNXsN66ZNn3NzFVyf4QKQV6thBDFgapZN5sYk2u0QD6pyc9Q7RaRwGzqLXdRFdF0KRLPx0lH9DsA0RJ1t85vuBbUK9f/0ys1w=
    file: prod_build/kalabox-$TRAVIS_TAG.$KBOX_PKG_TYPE
    skip_cleanup: true
    on:
      repo: kalabox/kalabox
      tags: true
  - provider: s3
    access_key_id: AKIAJO2C7GYG5GL5G74A
    secret_access_key:
      secure: Sr0cMoJ6ZtRSh4H6xwu/CV1pj5xaYgtE5vup80r4fDygfi5C/mFqzCOODWN928nzZHOXWkG13myhLgTztMYDkIkN+TIVP9BmHXpIqWaZsHeytrdLUJMSNsL1Dc8Ixm4kqJBqla9mRgjZaWYceDhbHFvdUZNA7s9Mr1fUUmGyYyI=
    bucket: installer.kalabox.io
    local-dir: dev_build
    acl: public_read
    region: us-west-2
    skip_cleanup: true
    on:
      repo: kalabox/kalabox
      branch: 1repo2ruleThemAll
