init:
  - git config --global core.autocrlf true
platform: x64
environment:
  nodejs_version: "4.2"

install:

  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64

  # Install InnoSetup
  - choco install -y InnoSetup
  - set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"

  # install relevant things
  - npm install -g grunt-cli bower
  - gem install sass

  # Build the things
  # Need to do this first because it installs JX for us
  - npm install

  # Sanity checks
  - node --version
  - npm --version
  - grunt --version
  - cmd: node_modules\jxcore\bin\jx.exe --version
  - cmd: node_modules\jxcore\bin\jx.exe --jxversion
  - ruby --version
  - gem --version
  - bower --version
  - sass --version
  # Iscc has no version option and returns exit code 1 by default
  # This can never fail but at least we can check the output to verify
  - iscc | echo

build_script:

  # Build dev releases
  - grunt pkg --dev
  - mkdir dev_build
  - copy dist\kalabox.exe dev_build\kalabox-latest-dev.exe

test_script:

  # Run basic tests
  - grunt test:code
  - grunt test:unit

artifacts:
  - path: dev_build\kalabox-latest-dev.exe
    name: development
  #- path: prod_build/kalabox-latest-dev.exe
  # name: production

after_build:
  - ps: Get-ChildItem .\dev_build\kalabox-latest-dev.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName s3 }
  #- ps: Get-ChildItem .\prod_build\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName github }
deploy:
  - provider: S3
    access_key_id:
      secure: t16g2geIvu5qJVSiPzqxzUnk4+p9X1psf6e8RmUJPDk=
    secret_access_key:
      secure: o/pYPIuDU8SPSrTB15BwzlLrDXGuhhTJUWdWMyvDLnsAwC6uJmASPEATUX9CFIEW
    bucket: installer.kalabox.io
    region: us-west-2
    artifact: s3
    on:
      branch: 1repo2ruleThemAll
  - provider: GitHub
    description: v$(KALABOX_VERSION)
    artifact: github
    draft: false
    auth_token:
      secure: h95XRXK3tAJOZphssQ9dB3rpdK0y2I8VpakCR79+YwjZQOCW4YukAdCcwtBFdEoD
    prerelease: false
    on:
      appveyor_repo_tag: true
notifications:
  - provider: Email
    to:
      - mike@kalabox.io
      - alec@kalabox.io
    on_build_status_changed: true
