init:
  - git config --global core.autocrlf true
platform: x64
environment:
  nodejs_version: "4.2"

install:

  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64

  # install relevant things
  - npm install -g grunt-cli

  # Build the things
  - npm install

  # Sanity checks
  - node --version
  - npm --version
  - grunt --version
  - node_modules/jxcore/bin/jx --version
  - node_modules/jxcore/bin/jx --jxversion

test_script:

  # Run basic tests
  - grunt test:code
  - grunt test:unit

build_script:

  # Build dev releases
  - grunt pkg --dev

artifacts:
  - path: dev_build/*.exe
    name: development
  - path: prod_build/*.exe
    name: production

after_build:
  - ps: Get-ChildItem .\dev_build\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName s3 }
  - ps: Get-ChildItem .\prod_build\*.exe | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name -DeploymentName github }
deploy:
  - provider: S3
    access_key_id:
      secure: t16g2geIvu5qJVSiPzqxzUnk4+p9X1psf6e8RmUJPDk=
    secret_access_key:
      secure: o/pYPIuDU8SPSrTB15BwzlLrDXGuhhTJUWdWMyvDLnsAwC6uJmASPEATUX9CFIEW
    bucket: cli.kalabox.io
    region: us-west-1
    artifact: s3
    on:
      branch: v0.12
  - provider: GitHub
    description: v$(KALABOX_VERSION)
    artifact: github
    draft: false
    auth_token:
      secure: h95XRXK3tAJOZphssQ9dB3rpdK0y2I8VpakCR79+YwjZQOCW4YukAdCcwtBFdEoD
    prerelease: false
    on:
      appveyor_repo_tag: true
notifications:
  - provider: Email
    to:
      - mike@kalabox.io
      - alec@kalabox.io
    on_build_status_changed: true
